services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
#    env_file: ".env"
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
