FROM php:8.3-fpm-alpine3.20

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apk add --no-cache make bash-completion nodejs npm

ENV TERM=xterm-256color
RUN echo "PS1='\e[92m\u\e[0m@\e[94m\h\e[0m:\e[35m\w\e[0m# '" >> /root/.bashrc


COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN set -eux; \
    install-php-extensions pdo_pgsql xdebug excimer;

COPY ./xdebug.ini "${PHP_INI_DIR}/conf.d"

WORKDIR /app

COPY . .

RUN composer install --no-interaction
#RUN npm ci
#RUN npm run build

CMD ["bash", "-c", "make start"]
#CMD ["tail", "-f", "/dev/null"]
